language: ruby
dist: trusty
cache: bundler
services:
  - postgresql
rvm:
  - 2.4.2
script:
  - bundle exec rake
before_install:
  - gem update bundler
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
