default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: refactored_enigma_development

test:
  <<: *default
  database: refactored_enigma_test

production:
  <<: *default
  database: refactored_enigma_production
  username: refactored_enigma
  password: <%= ENV['DATABASE_PASSWORD'] %>
